### ISSUE TITLE
Grouper 2.1.5 loses track of ldap connection

### ISSUE THREAD

**Issue by hanswesterbeek** [Internet2/grouper#43]
Hi,

I am having some issues with the LDAP connection pool managed by Grouper. When grouper first starts up, things are fine. After a period of inactivity (and this occurs more often than not on our test-stage), we are seeing the following exception.

Grouper does not recover from this connection failure. The only remedy I found until now is to restart it.

Is this a known issue? Do other workarounds exist?

```java
2015-06-16 10:55:34,772: [TP-Processor8] ERROR WsGetMembershipsResults.assignResultCodeException(384) - <  gadget - 10.0.0.122 > - clientVersion: 1.6.0, wsGroupLookups: null, wsMemberFilter: All, includeSubjectDetail: false, actAsSubject: null, fieldName: null, fieldType: null, subjectAttributeNames: null
, paramNames: 
, params: null
, wsSubjectLookups: Array size: 1: [0]: WsSubjectLookup[subjectId=urn:collab:person:example.com:admin]

, sourceIds: null
, scope: null, wsStemLookup: null, stemScope: null, enabled: null
, membershipIds: null
, wsStemLookups: null
, wsAttributeDefLookups: null
java.lang.RuntimeException: Cant find subject from login id: gadget
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee$1.callback(GrouperServiceJ2ee.java:261)
	at edu.internet2.middleware.grouper.GrouperSession.callbackGrouperSession(GrouperSession.java:803)
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee.retrieveSubjectLoggedIn(GrouperServiceJ2ee.java:246)
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee.retrieveSubjectActAsHelper(GrouperServiceJ2ee.java:358)
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee.retrieveSubjectActAs(GrouperServiceJ2ee.java:330)
	at edu.internet2.middleware.grouper.ws.util.GrouperServiceUtils.retrieveGrouperSession(GrouperServiceUtils.java:849)
	at edu.internet2.middleware.grouper.ws.GrouperServiceLogic.getMemberships(GrouperServiceLogic.java:1584)
	at edu.internet2.middleware.grouper.ws.coresoap.GrouperService.getMemberships(GrouperService.java:2428)
	at edu.internet2.middleware.grouper.ws.rest.GrouperServiceRest.getMemberships(GrouperServiceRest.java:1285)
	at edu.internet2.middleware.grouper.ws.rest.method.GrouperWsRestGet$7.service(GrouperWsRestGet.java:386)
	at edu.internet2.middleware.grouper.ws.rest.method.GrouperRestHttpMethod$1.service(GrouperRestHttpMethod.java:57)
	at edu.internet2.middleware.grouper.ws.rest.GrouperRestServlet.service(GrouperRestServlet.java:199)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee.doFilter(GrouperServiceJ2ee.java:659)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:558)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:745)
Caused by: edu.internet2.middleware.subject.SourceUnavailableException: Ldap NamingException: LDAP response read timed out, timeout used:-1ms.
	at edu.internet2.middleware.subject.provider.LdapSourceAdapter.getLdapResultsHelper(LdapSourceAdapter.java:704)
	at edu.internet2.middleware.subject.provider.LdapSourceAdapter.getLdapResults(LdapSourceAdapter.java:591)
	at edu.internet2.middleware.subject.provider.LdapSourceAdapter.getLdapUnique(LdapSourceAdapter.java:724)
	at edu.internet2.middleware.subject.provider.LdapSourceAdapter.getSubject(LdapSourceAdapter.java:314)
	at edu.internet2.middleware.subject.provider.BaseSourceAdapter.getSubjectByIdOrIdentifier(BaseSourceAdapter.java:164)
	at edu.internet2.middleware.grouper.subj.SourcesXmlResolver$4.callLogic(SourcesXmlResolver.java:517)
	at edu.internet2.middleware.grouper.subj.SourcesXmlResolver$4.callLogic(SourcesXmlResolver.java:514)
	at edu.internet2.middleware.grouper.subj.SourcesXmlResolver$LogLabelCallable.call(SourcesXmlResolver.java:170)
	at edu.internet2.middleware.grouper.subj.SourcesXmlResolver.executeCallables(SourcesXmlResolver.java:231)
	at edu.internet2.middleware.grouper.subj.SourcesXmlResolver.findByIdOrIdentifier(SourcesXmlResolver.java:523)
	at edu.internet2.middleware.grouper.subj.CachingResolver.findByIdOrIdentifier(CachingResolver.java:377)
	at edu.internet2.middleware.grouper.subj.ValidatingResolver.findByIdOrIdentifier(ValidatingResolver.java:202)
	at edu.internet2.middleware.grouper.SubjectFinder.findByIdOrIdentifier(SubjectFinder.java:160)
	at edu.internet2.middleware.grouper.ws.GrouperServiceJ2ee$1.callback(GrouperServiceJ2ee.java:254)
	... 31 more
Caused by: javax.naming.NamingException: LDAP response read timed out, timeout used:-1ms.; remaining name 'dc=sowewhere,dc=nl'
	at com.sun.jndi.ldap.Connection.readReply(Connection.java:483)
	at com.sun.jndi.ldap.LdapClient.getSearchReply(LdapClient.java:639)
	at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:562)
	at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1985)
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1847)
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1772)
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1789)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:412)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:394)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:376)
	at edu.vt.middleware.ldap.AbstractLdap.search(AbstractLdap.java:215)
	at edu.vt.middleware.ldap.Ldap.search(Ldap.java:431)
	at edu.vt.middleware.ldap.Ldap.search(Ldap.java:347)
	at edu.internet2.middleware.subject.provider.LdapSourceAdapter.getLdapResultsHelper(LdapSourceAdapter.java:701)
	... 44 more
```

**Comment by mchyzer** [comment]
Are there vt-ldap settings that might help?

Make an ldap.properties in your classpath and maybe try changing some of these:

https://code.google.com/p/vt-middleware/wiki/vtldapPooling


edu.vt.middleware.ldap.pool.validateOnCheckIn

false

whether connections should be validated when objects are returned to the pool

edu.vt.middleware.ldap.pool.validateOnCheckOut

false

whether connections should be validated when objects are loaned out from the pool

edu.vt.middleware.ldap.pool.validatePeriodically

false

whether connections should be validated periodically when the pool is idle

edu.vt.middleware.ldap.pool.pruneTimerPeriod

300000 (5 min)

period at which pool should be pruned

edu.vt.middleware.ldap.pool.validateTimerPeriod

1800000 (30 min)

period at which pool should be validated

edu.vt.middleware.ldap.pool.expirationTime

600000 (10 min)

time an object can stay in the pool before it is considered stale and available for pruning



edu.vt.middleware.ldap.operationRetry

1

specifies the number of times an LDAP operation will be retried if a retry exception occurs; set to -1 for infinite retries

edu.vt.middleware.ldap.operationRetryWait

0

the amount of time in milliseconds that LDAP operations should wait before retrying

edu.vt.middleware.ldap.operationRetryBackoff

0

factor by which to multiply the operation retry wait time; this allows clients to progressively delay each retry

edu.vt.middleware.ldap.operationRetryExceptions

{CommunicationException, ServiceUnavailableException}

exception classes to retry operations on; supports a comma delimited list for multiple values


Not sure if retry will get a new connection… maybe have retry as high as your pool size?  Validate on checkin?  Validate periodically?  Expire the connections after a minute?  Validate every minute?

Let us know if anything works

Thanks,
Chris

**Comment by hanswesterbeek** [comment]
Thank you, I will try adding said properties-file to the cp and report back.

**Comment by mchyzer** [comment]
What did you put in the properties file exactly to make it work?

**Comment by hanswesterbeek** [comment]
Just one line in `ldap.properties`:

```
edu.vt.middleware.ldap.pool.validateOnCheckOut=true
```

**Comment by mchyzer** [comment]
Fyi this fixed the issue:


Just one line in ldap.properties:


edu.vt.middleware.ldap.pool.validateOnCheckOut=true

Thanks Hans!

Chris


From: grouper-dev-request@internet2.edu [mailto:grouper-dev-request@internet2.edu] On Behalf Of Chris Hyzer
Sent: Monday, June 22, 2015 7:01 PM
To: Internet2/grouper; Internet2/grouper
Cc: grouper-dev@internet2.edu
Subject: [grouper-dev] RE: [grouper] Grouper 2.1.5 loses track of ldap connection (#43)

Are there vt-ldap settings that might help?

Make an ldap.properties in your classpath and maybe try changing some of these:

https://code.google.com/p/vt-middleware/wiki/vtldapPooling


edu.vt.middleware.ldap.pool.validateOnCheckIn

false

whether connections should be validated when objects are returned to the pool

edu.vt.middleware.ldap.pool.validateOnCheckOut

false

whether connections should be validated when objects are loaned out from the pool

edu.vt.middleware.ldap.pool.validatePeriodically

false

whether connections should be validated periodically when the pool is idle

edu.vt.middleware.ldap.pool.pruneTimerPeriod

300000 (5 min)

period at which pool should be pruned

edu.vt.middleware.ldap.pool.validateTimerPeriod

1800000 (30 min)

period at which pool should be validated

edu.vt.middleware.ldap.pool.expirationTime

600000 (10 min)

time an object can stay in the pool before it is considered stale and available for pruning



edu.vt.middleware.ldap.operationRetry

1

specifies the number of times an LDAP operation will be retried if a retry exception occurs; set to -1 for infinite retries

edu.vt.middleware.ldap.operationRetryWait

0

the amount of time in milliseconds that LDAP operations should wait before retrying

edu.vt.middleware.ldap.operationRetryBackoff

0

factor by which to multiply the operation retry wait time; this allows clients to progressively delay each retry

edu.vt.middleware.ldap.operationRetryExceptions

{CommunicationException, ServiceUnavailableException}

exception classes to retry operations on; supports a comma delimited list for multiple values


Not sure if retry will get a new connection… maybe have retry as high as your pool size?  Validate on checkin?  Validate periodically?  Expire the connections after a minute?  Validate every minute?

Let us know if anything works

Thanks,
Chris

**Comment by hanswesterbeek** [comment]
Oops, I was premature. Problem was not fixed. I will report back.

**Comment by hanswesterbeek** [comment]
It seems that my organization is using a obsolete(?) way of configuring sources. See [https://github.com/OpenConext/OpenConext-deploy/blob/develop/roles/grouper/templates/sources.xml.j2], it's using the GrouperJndiSourceAdapter. 

From the grouper documentation, it is not clear for me how to proceed.

Right now, it seems that grouper is ignoring my connection pool settings (it is initializing the pool at 3 connections even if I have set it to 5). See [https://github.com/OpenConext/OpenConext-deploy/blob/develop/roles/grouper/templates/ldap.properties.j2]

Here's some logging to illustrate my point:

```
2015-06-30 09:48:10,048: [main] DEBUG AbstractLdapPool.initialize(109) -  - beginning pool initialization
2015-06-30 09:48:10,052: [main] DEBUG AbstractLdapPool.initialize(117) -  - prune pool task scheduled
2015-06-30 09:48:10,053: [main] DEBUG AbstractLdapPool.initialize(125) -  - validate pool task scheduled
2015-06-30 09:48:10,053: [main] DEBUG AbstractLdapPool.initializePool(145) -  - checking ldap pool size >= 3
2015-06-30 09:48:10,078: [main] DEBUG AbstractLdapPool.initialize(131) -  - pool initialized to size 3
2015-06-30 09:48:10,083: [main] DEBUG AbstractLdapPool.initialize(109) -  - beginning pool initialization
2015-06-30 09:48:10,083: [main] DEBUG AbstractLdapPool.initialize(117) -  - prune pool task scheduled
2015-06-30 09:48:10,084: [main] DEBUG AbstractLdapPool.initialize(125) -  - validate pool task scheduled
2015-06-30 09:48:10,084: [main] DEBUG AbstractLdapPool.initializePool(145) -  - checking ldap pool size >= 3
2015-06-30 09:48:10,106: [main] DEBUG AbstractLdapPool.initialize(131) -  - pool initialized to size 3
2015-06-30 09:48:10,174: [main] WARN  ApiConfig.printConfigOnce(227) -  - Grouper starting up: version: 2.1.5, build date: 2013/10/03 15:50:12, env: <no label configured>
grouper.properties read from: /etc/tomcat6/appconf/grouper.properties
Grouper current directory is: /usr/share/tomcat6
log4j.properties read from:   /etc/tomcat6/appconf/log4j.properties
Grouper is logging to file:   /usr/share/tomcat6/logs/grouper.log, at min level WARN for package: edu.internet2.middleware.grouper, based on log4j.properties
grouper.hibernate.properties: /etc/tomcat6/appconf/grouper.hibernate.properties
grouper.hibernate.properties: grouperrw@jdbc:mysql://t03.dev.coin.surf.net:3306/grouper
sources.xml read from:        /etc/tomcat6/appconf/sources.xml
sources.xml groupersource id: g:gsa
sources.xml groupersource id: grouperEntities
sources.xml ldap source id:   applications: ldap.properties
sources.xml ldap source id:   openconext-ldap: ldap.properties
```

Should I configure Grouper differently? `sources.xml` has a lot of different settings and I have been reluctant to make changes as I am not a grouper expert.

**Comment by mchyzer** [comment]
Im looking in the source, and I think you need to specify the vt ldap properties file in the sources.xml…


    <init-param>
      <param-name> ldapProperties_file</param-name>
      <param-value>ldap.properties</param-value>
    </init-param>


But if you do this it seems you need to move all your connection settings and user/pass etc into the ldap.properties.  Can you try it and let us know?
If wiki updates would help and you have suggestions let me know and I can incorporate your suggestions

Thanks,
Chris

**Comment by oharsta** [comment]
Hi,

I'm a colleague of Hans and took over the problem we are having with invalid Ldap connections not being cleaned up after a Ldap restart. 

When I look into the source code (tag GROUPER_2_1_5) then I can't see how your suggestion could work. Basically the LdapSourceAdapter reads the properties file specified by ldapProperties_file. It uses the properties file to read the credentials and the additional key-values related to tuning the Ldap pool (e.g. edu.vt.middleware.ldap.pool.validateOnCheckOut) end up in DefaultLdapFactory#config#additionalEnvironmentProperties

However when the pool is created (LdapSourceAdapter#initializeLdap line 291):

    DefaultLdapFactory factory = new DefaultLdapFactory(ldapConfig);
     
      try {
         ldapPool = new SoftLimitLdapPool(factory);
         ldapPool.initialize();

the SoftLimitLdapPool constructor used is the one where the factory is supplied on the SoftLimitLdapPool and not the other constructor where also the LdapPoolConfig is provided. As such the SoftLimitLdapPool is initialized with a new default LdapPoolConfig and the tuning properties specified in the ldapProperties_file are never used. I debugged our test environment and confirmed this.

Maybe I'm missing something but I think using the single argument constructor for the SoftLimitLdapPool with only the factory being provided and not the LdapPoolConfig is a bug. Could you confirm this?

Again maybe I'm missing something, but when I examined the code I can't figure out where the SoftLimitLdapPool being used could ever pick up the tuning properties in the ldapProperties_file as it's creates a new default LdapPoolConfig which does not validate anything and has a DEFAULT_VALIDATE_ON_CHECKOUT of false.

**Comment by saltybeagle** [comment]
Related issue here https://bugs.internet2.edu/jira/browse/GRP-1148
